name             'arterys'
maintainer       'Rafik Benmansour'
maintainer_email 'raf_ben@hotmail.com'
license          'All rights reserved'
description      'Installs/Configures create'
long_description 'Installs/Configures create'
version          '0.1.0'
